#!/bin/bash

echo "scaling django deployent to 3 replicas"
kubectl scale deployment messaging-app-deployment --replicas=3

echo "Waiting for pods to become ready..."
kubectl rollout status deployment messaging-app-deployment

echo "check running pods..."
kubectl get pods -l app=messaging-app -o wide

POD_NAME=$(kubectl get pods -l app=messaging-app -o jsonpath='{.items[0].metadata.name}')
echo "🔗 Port-forwarding pod $POD_NAME on port 8000..."
kubectl port-forward "$POD_NAME" 8000:8000 &
PF_PID=$!
sleep 5

if ! command -v wrk &> /dev/null
then
    echo "wrk not found. please install wrk"
else
    echo "Running load test with wrk (10s, 12 threads, 400 connections)..."
    wrk -t12 -c400 -d10s http://127.0.0.1:8000/
fi

kill $PF_PID >/dev/null 2>&1

echo "Resource usage for pods"
kubectl top pods

echo "Done."